name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Create secure config
      run: |
        echo "// 安全配置 - 由 GitHub Actions 自動生成" > shared/secure-config.js
        echo "window.SECURE_CONFIG = {" >> shared/secure-config.js
        echo "  GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'," >> shared/secure-config.js
        echo "  GOOGLE_APPS_SCRIPT_URL: '${{ secrets.GOOGLE_APPS_SCRIPT_URL }}'" >> shared/secure-config.js
        echo "};" >> shared/secure-config.js
        echo "Generated secure config:"
        cat shared/secure-config.js
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4